set -sg escape-time 10

set -g base-index 1
set -g pane-base-index 1

set -g mode-keys vi
set -g default-terminal "xterm-256color"

set -g mouse on
# set -g xterm-keys on

bind r source-file ~/.tmux.conf \; display "Reloaded!"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r H resize-pane -L 20
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 20

bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
